#!/bin/bash
# kurbeScript.sh

# Objective: start a local kubernetes, verify the cluster and list the pod

# Exit immediately if the command exisat with a non-zero status
set -e

echo "Starting Kubernetes setup..."

# check if minikube is installed
echo "Checking if Minikube is installed..."
if ! command -v minikube &> /dev/null
then
    echo "Installing minikube via Homebrew..."
    brew install minikube
else
    echo "Minikube already installed"
fi

# check if kubernetes is installed
if ! command -v kubectl &> /dev/null
then
    echo "Installing kuberctl..."
    brew install kubectl
    echo "kubectl installed successfully"
else
    echo "Kubectl already installed"
fi


# start minikube cluster
echo "starting minikube clutser using docker driver..."
minikube start --driver=docker

# Verify the kubernetes cluster info
echo "Verifying the kubernetes cluster informations..."
kubectl cluster-info

echo "Checking minikube status..."
minikube status


# Retrieve all available pods
echo "Listing all the available pods and namespace..."
kubectl get pods --all-namespaces

# Display the nodee and namespace
echo "Checking cluster node and namespace"
kubectl get nodes
kubectl get namespaces

echo -e "\n kubernetes cluster is up and running.."
echo "Set up commpleted successfully"



